# Generated by Django 2.2.12 on 2020-05-25 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionarySource',
            fields=[
                ('abbrv', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='What is the primary title of the dictionary source?', max_length=256)),
                ('author', models.CharField(blank=True, help_text='Separate multiple authors with commas. See also: editor', max_length=512)),
                ('editor', models.CharField(blank=True, help_text='Who edited or compiled this volume? Separate multiple editors with commas.', max_length=512)),
                ('year', models.IntegerField(blank=True, help_text='What year was this dictionary published?', null=True)),
                ('publisher', models.CharField(blank=True, help_text='What was the publisher?', max_length=128)),
                ('city', models.CharField(blank=True, help_text='What is the city of the publisher?', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Wordform',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=40)),
                ('full_lc', models.CharField(help_text='Full lexical category directly from source', max_length=10)),
                ('pos', models.CharField(choices=[('IPV', 'IPV'), ('PRON', 'PRON'), ('N', 'N'), ('IPC', 'IPC'), ('V', 'V'), ('', '')], help_text='Part of speech parsed from source. Can be unspecified', max_length=4)),
                ('analysis', models.CharField(default='', help_text='fst analysis or the best possible generated if the source is not analyzable', max_length=50)),
                ('is_lemma', models.BooleanField(default=False, help_text="The wordform is chosen as lemma. This field defaults to true if according to fst the wordform is not analyzable or it's ambiguous")),
                ('as_is', models.BooleanField(default=False, help_text='The lemma of this wordform is not determined during the importing process.is_lemma defaults to true and lemma field defaults to self')),
                ('lemma', models.ForeignKey(help_text='The identified lemma of this wordform. Defaults to self', on_delete=django.db.models.deletion.CASCADE, related_name='inflections', to='morphodict.Wordform')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishKeyword',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_keyword', to='morphodict.Wordform')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('citations', models.ManyToManyField(to='morphodict.DictionarySource')),
                ('wordform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='morphodict.Wordform')),
            ],
        ),
        migrations.AddIndex(
            model_name='wordform',
            index=models.Index(fields=['analysis'], name='morphodict__analysi_4db49f_idx'),
        ),
        migrations.AddIndex(
            model_name='wordform',
            index=models.Index(fields=['text'], name='morphodict__text_388fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='englishkeyword',
            index=models.Index(fields=['text'], name='morphodict__text_e45eb0_idx'),
        ),
    ]
