# Generated by Django 2.2.15 on 2020-11-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionarySource',
            fields=[
                ('abbrv', models.CharField(help_text='A short identifier for the dicionary source', max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='What is the primary title of the dictionary source?', max_length=256)),
                ('editor', models.CharField(blank=True, help_text='Who edited or compiled this volume? Separate multiple editors with commas.', max_length=512)),
                ('import_filename', models.CharField(editable=False, help_text='The file that imported these entries', max_length=128)),
                ('last_import_sha384', models.CharField(editable=False, help_text='SHA-384 hash (hexadecimal) of the imported file', max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('entry_id', models.CharField(help_text='Unique ID for this head.', max_length=8, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=64)),
                ('word_class', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['text'],
                'unique_together': {('text', 'word_class')},
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('citations', models.ManyToManyField(to='morphodict.DictionarySource')),
                ('defines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='morphodict.Head')),
            ],
        ),
    ]
