# Generated by Django 2.2.12 on 2020-05-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphodict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionarysource',
            name='last_import_sha512',
        ),
        migrations.AddField(
            model_name='dictionarysource',
            name='last_import_sha384',
            field=models.CharField(default='', editable=False, help_text='SHA-384 hash (hexadecimal) of the imported file', max_length=96),
            preserve_default=False,
        ),
    ]
