# Generated by Django 2.2.15 on 2020-11-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morphodict', '0001_initial'),
        ('gunaha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onespotduplicate',
            name='duplicate_of',
            field=models.ForeignKey(help_text='The entry that is a duplicate of.', on_delete=django.db.models.deletion.CASCADE, to='morphodict.Head'),
        ),
        migrations.AlterField(
            model_name='onespotduplicate',
            name='entry_id',
            field=models.CharField(help_text='Onespot ID of the duplicate entry', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_audio', models.FileField(upload_to='recordings')),
                ('entry', models.ForeignKey(help_text='recording of what head?', on_delete=django.db.models.deletion.CASCADE, to='morphodict.Head')),
            ],
        ),
    ]
